#!/bin/sh

# Set these paths appropriately

BIN=/Users/atreat/dev/moses/tree-tagger/bin
CMD=/Users/atreat/dev/moses/tree-tagger/cmd
LIB=/Users/atreat/dev/moses/tree-tagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/russian-utf8.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
