#!/bin/bash

# Resolve the directory containing this script taken from http://stackoverflow.com/a/246128
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

# Set these paths appropriately

BIN=$DIR/../tree-tagger/bin
CMD=$DIR/../tree-tagger/cmd
LIB=$DIR/../tree-tagger/lib

OPTIONS="-token -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/tibetan-syllables-utf8.par

$TOKENIZER -e $* |
# remove empty lines
grep -v '^$' |
# tagging
$TAGGER $OPTIONS $PARFILE |
perl -pe 's/\tV[BDHV]/\tVB/;s/\tIN\/that/\tIN/;'
