#!/bin/sh

# Set these paths appropriately

BIN=/Users/atreat/dev/moses/tree-tagger/bin
CMD=/Users/atreat/dev/moses/tree-tagger/cmd
LIB=/Users/atreat/dev/moses/tree-tagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/italian-abbreviations
PARFILE=${LIB}/italian-utf8.par

$TOKENIZER -i -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
